name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          repo-token: '${{ secrets.LHCI_GITHUB_APP_TOKEN }}'
      - run: npm install
      - run: npm run build
      # - name: Lighthouse CI //This is a nice approach, We will use at future.
      #   env:
      #     LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      #   run: |
      #     npm install -g @lhci/cli@0.4.x
      #     lhci autorun
      - name: Install Vue-cli to run Test and Lint
        run: |
          npm run global add @vue/cli @vue/cli-service-global
      - run: npm run test:unit
      - run: npm run lint
